'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { api,json } from '../lib/projects';
import type { Session } from '../lib/accounts';
export default function Login(){
 const router=useRouter();const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{void api<Session>('auth/session').then(s=>{if(s.authenticated)router.replace('/account');}).catch(()=>{}).finally(()=>setReady(true));},[router]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget);if(register&&data.get('password')!==data.get('confirm')){setError('The passwords do not match.');return;}setBusy(true);try{await api<Session>(`auth/${register?'register':'login'}`,json('POST',{email:data.get('email'),password:data.get('password'),...(register?{name:data.get('name')}: {})}));router.push('/account');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="admin-shell"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">a<span>.</span></span><span>ablests<small>DIGITAL SOLUTION</small></span></Link><Link className="text-link" href="/">Back to website</Link></header><main className="admin-login"><p className="eyebrow">YOUR PRIVATE CLIENT AREA</p><h1>{register?'Create your account.':'Welcome back.'}</h1><p>{register?'Save your personal and business details in your private profile.':'Sign in to view and update your profile.'}</p><form onSubmit={submit}><fieldset disabled={busy||!ready} className="auth-fields">{register&&<label>Your name<input name="name" required autoComplete="name" maxLength={100}/></label>}<label>Email address<input name="email" type="email" required autoComplete="username" maxLength={200}/></label><label>Password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete={register?'new-password':'current-password'}/></label>{register&&<><label>Confirm password<input name="confirm" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><p className="form-note">Use at least 12 characters for your password.</p></>}<p role="alert" className="admin-error">{error}</p><button type="submit" className="button">{busy?'Please wait…':register?'Create account':'Sign in'}</button></fieldset></form><p className="auth-switch">{register?'Already have an account?':'New client?'} <button className="text-button" disabled={busy||!ready} onClick={()=>{setRegister(!register);setError('');}}>{register?'Sign in':'Create an account'}</button></p></main></div>;
}
