'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { api,json } from '../lib/projects';
import type { Account } from '../lib/accounts';
export default function ClientAccount(){
 const router=useRouter();const [user,setUser]=useState<Account|null>(null),[profile,setProfile]=useState({name:'',company:'',phone:''}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setError('');try{const account=await api<Account>('account');setUser(account);setProfile({name:account.name,company:account.company,phone:account.phone});}catch(e){if((e as Error & {status?:number}).status===401)router.replace('/login');else setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');try{setUser(await api<Account>('account',json('PATCH',profile)));setMessage('Your profile has been saved.');}catch(e){if((e as Error & {status?:number}).status===401)router.replace('/login');else setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="admin-shell"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">a<span>.</span></span><span>ablests<small>DIGITAL SOLUTION</small></span></Link><div><Link className="text-link" href="/">Website</Link>{user?.role==='admin'&&<Link className="secondary-button" href="/admin">Admin</Link>}{user&&<button className="secondary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('auth/logout',{method:'POST'});router.replace('/');}catch(e){setError((e as Error).message);setBusy(false);}}}>Sign out</button>}</div></header><main className="admin-main"><div className="admin-title"><div><p className="eyebrow">MY ACCOUNT</p><h1>{user?`Hello, ${user.name}.`:'Your account'}</h1><p>Your personal and business details, in one place.</p></div></div><p role="alert" className="admin-error">{error}</p><p role="status" className="admin-success">{message}</p>{!user?<>{!error?<p role="status">Loading your account…</p>:<button className="button" onClick={load}>Try again</button>}</>:<div className="profile-workspace"><section className="admin-editor"><h2>Your profile</h2><p className="account-email">{user.email}</p><form onSubmit={save}><fieldset className="auth-fields" disabled={busy}><label>Name<input required maxLength={100} autoComplete="name" value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Company<input maxLength={150} autoComplete="organization" value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})}/></label><label>Phone<input maxLength={40} autoComplete="tel" type="tel" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><button className="button" type="submit">{busy?'Saving…':'Save profile'}</button></fieldset></form></section></div>}</main></div>;
}
